FROM dockerhub.mos.ru/node:16.14.2-alpine  as build
ENV CI=false
ARG APIGATE_BACK_ENV
ARG APIGATE_BACK_PORT
ARG APIGATE_BACK_EMAIL_HOST
ARG APIGATE_BACK_EMAIL_PORT
ARG APIGATE_BACK_EMAIL_USER
ARG APIGATE_BACK_EMAIL_PASS
ARG APIGATE_BACK_EMAIL_SECURE_CONNECTION
ARG APIGATE_BACK_EMAIL_SECURE
ARG APIGATE_BACK_EMAIL_TLS
ARG APIGATE_BACK_EMAIL_REJECT_UNAUTH
ARG APIGATE_BACK_EMAIL_REJECT_FROM
ARG APIGATE_BACK_EMAIL_RESTART_NOTIFY_ENVS
ARG APIGATE_BACK_ALERT_EMAIL
ENV APIGATE_BACK_ENV=$APIGATE_BACK_ENV
ENV APIGATE_BACK_PORT=$APIGATE_BACK_PORT
ENV APIGATE_BACK_EMAIL_HOST=$APIGATE_BACK_EMAIL_HOST
ENV APIGATE_BACK_EMAIL_PORT=$APIGATE_BACK_EMAIL_PORT
ENV APIGATE_BACK_EMAIL_USER=$APIGATE_BACK_EMAIL_USER
ENV APIGATE_BACK_EMAIL_PASS=$APIGATE_BACK_EMAIL_PASS
ENV APIGATE_BACK_EMAIL_SECURE_CONNECTION=$APIGATE_BACK_EMAIL_SECURE_CONNECTION
ENV APIGATE_BACK_EMAIL_SECURE=$APIGATE_BACK_EMAIL_SECURE
ENV APIGATE_BACK_EMAIL_TLS=$APIGATE_BACK_EMAIL_TLS
ENV APIGATE_BACK_EMAIL_REJECT_UNAUTH=$APIGATE_BACK_EMAIL_REJECT_UNAUTH
ENV APIGATE_BACK_EMAIL_REJECT_FROM=$APIGATE_BACK_EMAIL_REJECT_FROM
ENV APIGATE_BACK_EMAIL_RESTART_NOTIFY_ENVS=$APIGATE_BACK_EMAIL_RESTART_NOTIFY_ENVS
ENV APIGATE_BACK_ALERT_EMAIL=$APIGATE_BACK_ALERT_EMAIL

WORKDIR '/app'
COPY . /app

RUN npm config set registry https://repo-mirror.mos.ru/repository/npm-public
RUN npm get registry
RUN npm install pm2@5.1.2 --registry https://repo-mirror.mos.ru/repository/npm-public -g
RUN npm install

COPY . .
EXPOSE 4001
CMD ["pm2-runtime", "app.js"]

